### ISSUE TITLE
Missing Variable: Input Audio On/Off + Audio Feedback not working

### ISSUE THREAD

**Issue by Sam-D03** [bitfocus/companion-module-studiocoast-vmix#155] opened 2022-03-10 23:45 UTC
**Describe the bug**
I think the variable for an Input's Audio On/Off has been omitted from this release?
**To Reproduce**
Not in the variables list - plus also the Feedback **Audio - Input mute** is not functioning correctly either.

**Expected behavior**
When the input's audio is enabled (unmuted) in vmix, this should present as a variable and have feedback working to see when an input's audio is muted/unmuted.

**System (please complete the following information):**
Windows 11
- Companion Version [e.g. v2.2.0+4000-beta-7ced5d7f]
- vMix version [e.g. v24.0.0.72]

**Comment by thedist** [comment] 2022-03-11 21:10
Fixed in the latest commit 5c3a50643eec23634f1047d0e14035f1d786c34c

Feedback should work as intended, and I've added 2 instance variables:
- `${vmix:input_<GUID, Number, or Name>_mute}` 
- `${vmix:input_<GUID, Number, or Name>_audio}`. 

They're exactly the same thing but the inverse of eachother, so if input 1 is muted, then `${vmix:input_1_mute}` will be `true`, and `${vmix:input_1_audio}` will be `false`. So users can use whichever seems more intuitive for them as I know some programs use a red button to indicate when something is muted, and vMix in places uses a green `audio` button to indicate when something is not muted.

I'll close the issue when the module is updated in Companion.

**Closed** 2022-03-12 10:15 UTC
Labels: bug
