### ISSUE TITLE
Short Name in Feedback

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-studiocoast-vmix#43] opened 2020-09-14 17:16 UTC
I am using the input name for inputs now and it works well. But is it possible to use the GUID to contact inputs and have the  Short name show as feedback?
Also the title of a playing clip?

Thanks,
Steve

**Comment by daniep01** [comment] 2020-10-01 18:11
Hi, maybe related, I am attempting to use the GUID both in the action and in the instance feedback for the button. It seems fine in the action (quick play input to program) but not in the change colour based on live input feedback. Is this to be expected? 

Version 2.1.1

**Comment by McHauge** [comment] 2020-10-13 12:31
> Hi, maybe related, I am attempting to use the GUID both in the action and in the instance feedback for the button. It seems fine in the action (quick play input to program) but not in the change colour based on live input feedback. Is this to be expected?
> 
> Version 2.1.1

Yes, this is expected behaviour, except I did not think you could use the GUID in the actions as well. The reason you can't use GUID in feedbacks is that the API does not specify the current GUID in most cases that we check and only the input number, at least for now.

but will do some testing with it in the coming days, if I find a way to add the GUID support I add it, but no promise yet.

**Comment by McHauge** [comment] 2020-11-10 23:43
You can now use GUID's as inputs in both actions and feedbacks, at least at next pull into the core.

**Comment by McHauge** [comment] 2021-01-11 07:02
gonna close this, since it's now a part of the beta's

**Closed by McHauge** 2021-01-11 07:02 UTC
