### ISSUE TITLE
Feedback: Tally - Preview/Program state  - better way to write image data by Companion

### ISSUE THREAD

**Issue by Howlswolf** [bitfocus/companion-module-studiocoast-vmix#167] opened 2022-05-30 16:18 UTC
**Describe the feature**
Being able to use the Tally Layers + full feedback (without image) on the same button

**Is this version dependent (vMix v24.)?**
tested on vMix v25.0.0.31
Companion : 2.2.0+4184-beta-292fd517

**If documentation is required to implement, do you know where to find it?**

https://user-images.githubusercontent.com/87432144/171029367-13d03c84-f563-427c-aa4b-64f7fe963e13.mp4
at 21sec we can see that it is not working like we would like.

**Usecases**
Have feedbacks on an input button when its on Preview/Program and at the same time when its a Layer of a Input on Preview/Program

**Comment by Julusian** [comment] 2022-07-28 09:52
Duplicate of #150

It does read a little differently, but I think it ends up as the same problem internally

**Closed by Julusian** 2022-07-28 09:52 UTC
Labels: enhancement
