### ISSUE TITLE
Layer's title value no longer available as feedback

### ISSUE THREAD

**Issue by jarihakkarainen** [bitfocus/companion-module-studiocoast-vmix#142] opened 2022-02-08 15:33 UTC
**Describe the bug**
Some versions ago there used to be a way to add a Title Input's value as feedback to a button. That is no longer available?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**

- companion-2.2.0+3874-master-8f05f9f1
- vMix version 24.0.0.72

**Additional context**

**Comment by thedist** [comment] 2022-02-08 17:37
The module just underwent a major rewrite, and one of the things that was deprecated was layer title as a feedback. It was intended to be an instance variable and a fix is awaiting being merged to Companions Beta builds.

To access titles it'll be `$(vmix:input_1_layer_0_text)` where the `1` can be the inputs number, name, or key, and the `0` is the index of the title layer.

**Closed** 2022-02-28 12:25 UTC
Labels: bug
