### ISSUE TITLE
Vmix Presets Vmix Lists "Select Index 1"missing Edit field index #

### ISSUE THREAD

**Issue by Hitower78** [bitfocus/companion-module-studiocoast-vmix#288] opened 2024-10-11 07:25 UTC
**Describe the bug**

The Preset Press Action is the same als the "Prev photo", 
Feedback  is OK i think . I miss the Select Index field in the EDIT field
The buttonpress is the same as "Prev Photo" so slide or Playlist back

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Presets, Vmix, Slides and Lists
2. Click on 'select Index'

**Expected behaviour**
The field to enter the INDEX is missing and the API command is wrong i think. 
I use this Button years ago (i dont remember excactly) with powerpoint slides to jump to a specific slide.

**Screenshots**
not available

**System (please complete the following information):**

- Companion Version [3.2.2 / 3.4]
- vMix version [e.g. v27]

**Additional context**

**Comment by thedist** [comment] 2024-10-14 14:13
Thanks for the report. I've got a fix for this ready for this, which should be in one of the beta releases later today or tomorrow, and the stable release when Companion does the next stable release.

Until then, you can just add the action `Lists - Select Specific Picture/Slide/Index` manually to a button, as the issue is just with the preset having the wrong action set, so if you don't use the preset and just manually add the correct action to a button it'll work fine.

**Closed** 2024-10-15 13:40 UTC
Labels: bug

**Comment by Hitower78** [comment] 2024-11-27 23:17
Since Presets are available... i didnt use manually Edits anymore :-P 
Thanks
