### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by jbrown3925** [bitfocus/companion-module-studiocoast-vmix#30] opened 2020-07-13 03:42 UTC
Hi would it be possible to add input name as a feedback item where the Name can be updated with the short name of the selected input number. That way when naming in VMIX they are updated on the control sources.

**Comment by McHauge** [comment] 2020-08-18 10:56
@jbrown3925 not sure I understand what you want to do, currently you can use both input ID (eg 1,2,3...) and the short name in all input text boxes. what I understand you want to do is maybe bind input 1-8 on a streamdeck and then dynamically show the short name instead, as a way to use the same companion setup with many vmix profiles. Is this correctly understood?

**Comment by McHauge** [comment] 2020-08-18 11:26
@jbrown3925 I have now added a Variable that loads the short title, so when ever you wan't to use it in a setup, just type: $(vmix:input_1_name) in the title of the action and ofcource replace the number with the input you want.

**Comment by stevespaw** [comment] 2020-09-22 13:25
@McHauge This is similar to my request #43 
I cannot get these variables above to work, I am on the latest build.
Thanks!

**Comment by McHauge** [comment] 2020-09-22 17:14
@stevespaw are you on the latest release, or on the latest beta. You will need to be on the latest beta for these to work. and you should be able to see them in the companion module config page if not. then you're on the wrong version.

**Comment by McHauge** [comment] 2020-09-22 17:16
here is a picture that shows how it should look, and also that it has loaded the two inputs with colorbars: 
![image](https://user-images.githubusercontent.com/31018035/93915298-1d380e00-fd08-11ea-87e4-a93b03fdd775.png)

**Comment by krocheck** [comment] 2020-09-22 17:19
We had a regression issue in a commit (a lot of module were rolled back), so later today I a going to push a build that corrects that.  The version in current builds is v1.2.3, so not sure if that's relevant to @stevespaw getting this to work.

**Comment by McHauge** [comment] 2020-09-22 17:31
> We had a regression issue in a commit (a lot of modules were rolled back), so later today I am going to push a build that corrects that. The version in current builds is v1.2.3, so not sure if that's relevant to @stevespaw getting this to work.

yes, this need's v. 1.2.5 or higher to work. so that is probably why

**Comment by stevespaw** [comment] 2020-09-22 17:50
I am on -
companion-2.1.1-2dc0b1e-2586-win64.exe

So is this based on the GUID or the vMix "input number" ? 
Hopefully the GUID for it to track vMix changes

Thanks

**Comment by McHauge** [comment] 2020-09-22 18:24
> I am on -
> companion-2.1.1-2dc0b1e-2586-win64.exe
> 
> So is this based on the GUID or the vMix "input number" ?
> Hopefully the GUID for it to track vMix changes
> 
> Thanks

yes this lists the name of x input. so if you change the name of the input this changes. also these wil only be added if you have vmix running. and a input exists in vmix. from what i can see you would need to use a older version from before the rollback, or wait a day or to until @krocheck updates compainion to include the v1.2.6 of the module.

if you download build: 2.1.1 (2de1549-2569) from about 2 weeks ago it should work

**Comment by stevespaw** [comment] 2020-09-22 18:31
I will wait - Thanks!!

**Comment by McHauge** [comment] 2020-09-22 18:36
> I will wait - Thanks!!

great, but to clarify, since I think my message was a bit blurry, it does not use the input GUID, but the input number. I'm not sure what would be the best way to add/use GUID both as an input on functions/feedback. but also the title feedback for it. without having the need for 100+ variables at a time.

**Comment by stevespaw** [comment] 2020-09-22 19:07
> without having the need for 100+ variables at a time.
Yes, is this a problem :-) ?  This would give use real interactivity with the vMix Project. I know that the scope of this could be huge, but a game change in vMix project organization. Currently it requires a very rigid setup of vMix that can break easily. So if you just move an input with the current setup it changes the Companion button? To make this work- the GUID of all inputs should be read in and Short names, Long names and input numbers, These should be the output variables.  Now we have something :-) 

Thanks for listening,
Steve

**Comment by McHauge** [comment] 2020-09-22 20:43
> > without having the need for 100+ variables at a time.
> > Yes, is this a problem :-) ?  This would give use real interactivity with the vMix Project. I know that the scope of this could be huge, but a game change in vMix project organization. Currently it requires a very rigid setup of vMix that can break easily. So if you just move an input with the current setup it changes the Companion button? To make this work- the GUID of all inputs should be read in and output - Short names, Long names and input numbers, These should be the output variables.  Now we have something :-)
> 
> Thanks for listening,
> Steve

this is true, it's mostly because of the length of the list, but currently, you can use the input names as variables in all cases where you can set an input. this way the button will still be correct even if you move it. If you use the GUID, you would have the opposite problem where if you misclicked and closed an input all buttons that act on it would fail/ have to be updated. where the current use of input names, vs id, would allow you to just add a new one and rename it with the old name. the only inputs where this does not work is with the list input and calls, unless you rename your calls to like "call 1", "call 2" nd so on then it would only be the list input that would be afected by this, since it changes name based on what is being played.

**Comment by stevespaw** [comment] 2020-09-22 20:53
But if the user renames an input, it breaks the button currently- correct?
But it will be re-available in Companion to be typed in again - correct?
Still not a pull down input selector in Companion, so a typo is still a thing?

So that is the trade off. The current tool will save step of renaming the button, as an example

**Comment by McHauge** [comment] 2020-09-22 21:09
the naming variables, for now, is basically just for use in the button title, since it's read from the input ID.

So yes a user could rename something, and it would break, but it could easily be renamed back. where the GUID being tied to the input itself would disappear if closed, and you will need to redo all actions where it was used when adding a new one. from my point that is a verse thing to happen that renaming an input. but I feel like we are using vmix for very different things. where my setup is changing day by day, event by event. and I feel yours is more a locked setup where you aren't the operator but you configure the basic setup for use regularly. might be wrong but it that case yours might be more useful but would not work well in my flow.

with the drop-down thing, I personally don't see any way to make that a reliable option that would set it up better than it is currently. with how flexible and how different people use and set up their vmix. and with the drop-down both allow for the case where you want your buttons to act based on ID/placing in the layout (maybe for having a couple of flexible inputs) and still work great with constant inputs where the order in vmix might change.

but still, this is how I feel about it

**Comment by McHauge** [comment] 2020-11-10 23:44
You can now use GUID's as inputs in both actions and feedbacks, at least at next pull into the core. I feel like that is a good compromise, for now, that way you can use them if you want to.

**Comment by stevespaw** [comment] 2020-11-11 12:49
> You can now use GUID's as inputs in both actions and feedbacks, at least at next pull into the core. I feel like that is a good compromise, for now, that way you can use them if you want to.

Thanks for this update - we have a use case that this will be good for!

**Comment by TreborKutscher** [comment] 2020-11-17 19:04
What i would like to have is the ability to set input contrbution to audio bus as an absolute command.

I Like the way you did with the  Multiview Overlay Funktion, where you can define via dropdown wether toggle, set on, set off.

The current toggle only is too unprecise for complex routing scenarios

**Comment by McHauge** [comment] 2020-11-17 20:22
> What i would like to have is the ability to set input contrbution to audio bus as an absolute command.
> 
> I Like the way you did with the Multiview Overlay Funktion, where you can define via dropdown wether toggle, set on, set off.
> 
> The current toggle only is too unprecise for complex routing scenarios

this is currently a possibility in the next version (at least I think so)

**Comment by McHauge** [comment] 2021-01-11 07:11
@TreborKutscher you should now be able to have a dropdown whether to toggle, set on, set off. for the audio routing on inputs to buses, in the same way, as you can with bus to bus.

Also since the first part of the request is also included in the current betas I'll close this for now.

**Closed by McHauge** 2021-01-11 07:11 UTC
Labels: enhancement
